# Use Node.js base image
FROM node:lts-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application code
COPY . .

# Expose the port that your Next.js app runs on
EXPOSE 3000

# Start the Next.js app with development mode
CMD ["npm", "run", "dev"]
