version: '3'
services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - AUTH0_SECRET=${AUTH0_SECRET}
      - AUTH0_BASE_URL=${AUTH0_BASE_URL}
      - AUTH0_ISSUER_BASE_URL=${AUTH0_ISSUER_BASE_URL}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - API_URL=http://server:5000
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - NEXTAUTH_URL=http://client:3000
      - NEXTAUTH_URL_INTERNAL=http://client:3000
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    ports:
      - 3000:3000
    depends_on:
      - server

  server:
    build: ./server
    environment:
      - AUTH0_ISSUER_BASE_URL=${AUTH0_ISSUER_BASE_URL}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - DB_URL=${DB_URL}
      - REDIS_URL=redis://redis:6379
    ports:
      - 5000:5000
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379
