export const mapping = {
  US: "United States",
  GB: "United Kingdom",
  FR: "France",
  DE: "Germany",
  IT: "Italy",
  CA: "Canada",
  AU: "Australia",
  JP: "Japan",
  IN: "India",
  BR: "Brazil",
  ZA: "South Africa",
  NL: "Netherlands",
  ES: "Spain",
  SE: "Sweden",
  CH: "Switzerland",
  NO: "Norway",
  NZ: "New Zealand",
  MX: "Mexico",
  CN: "China",
  RU: "Russia",
  KR: "South Korea",
  SG: "Singapore",
  TH: "Thailand",
  MY: "Malaysia",
  ID: "Indonesia",
  PH: "Philippines",
  AE: "United Arab Emirates",
  SA: "Saudi Arabia",
  TR: "Turkey",
  IR: "Iran",
  EG: "Egypt",
  NG: "Nigeria",
  KE: "Kenya",
  UA: "Ukraine",
  PL: "Poland",
  RO: "Romania",
  CZ: "Czech Republic",
  BE: "Belgium",
  AT: "Austria",
  HU: "Hungary",
  SK: "Slovakia",
  PT: "Portugal",
  IE: "Ireland",
  GR: "Greece",
  FI: "Finland",
  DK: "Denmark",
  IL: "Israel",
  AR: "Argentina",
  CL: "Chile",
  CO: "Colombia",
  PE: "Peru",
  VE: "Venezuela",
  PK: "Pakistan",
  BD: "Bangladesh",
  VN: "Vietnam",
  TW: "Taiwan",
  HK: "Hong Kong",
  ZA: "South Africa",
  TZ: "Tanzania",
  UG: "Uganda",
  DZ: "Algeria",
  MA: "Morocco",
  GH: "Ghana",
  AO: "Angola",
  MZ: "Mozambique",
  ZW: "Zimbabwe",
  CM: "Cameroon",
  CI: "Ivory Coast",
  SN: "Senegal",
  MG: "Madagascar",
  NE: "Niger",
  BF: "Burkina Faso",
  ML: "Mali",
  TD: "Chad",
  ET: "Ethiopia",
  SO: "Somalia",
  LR: "Liberia",
  SL: "Sierra Leone",
  GW: "Guinea-Bissau",
  BI: "Burundi",
  TJ: "Tajikistan",
  TM: "Turkmenistan",
  GE: "Georgia",
  AM: "Armenia",
  AZ: "Azerbaijan",
  BY: "Belarus",
  MD: "Moldova",
  AL: "Albania",
  MK: "North Macedonia",
  MT: "Malta",
  IS: "Iceland",
  LU: "Luxembourg",
  MC: "Monaco",
  LI: "Liechtenstein",
  SM: "San Marino",
  VA: "Vatican City",
  AD: "Andorra",
  AG: "Antigua and Barbuda",
  BS: "Bahamas",
  BB: "Barbados",
  BZ: "Belize",
  BJ: "Benin",
  BT: "Bhutan",
  BO: "Bolivia",
  BW: "Botswana",
  BN: "Brunei",
  BG: "Bulgaria",
  BF: "Burkina Faso",
  BI: "Burundi",
  CV: "Cabo Verde",
  KH: "Cambodia",
  CM: "Cameroon",
  CF: "Central African Republic",
  TD: "Chad",
  KM: "Comoros",
  CG: "Congo (Brazzaville)",
  CD: "Congo (Kinshasa)",
  CR: "Costa Rica",
  CI: "Côte d'Ivoire",
  HR: "Croatia",
  CU: "Cuba",
  CY: "Cyprus",
  DJ: "Djibouti",
  DM: "Dominica",
  DO: "Dominican Republic",
  GQ: "Equatorial Guinea",
  ER: "Eritrea",
  EE: "Estonia",
  SZ: "Eswatini",
  FJ: "Fiji",
  GD: "Grenada",
  GT: "Guatemala",
  GN: "Guinea",
  GY: "Guyana",
  HT: "Haiti",
  HN: "Honduras",
  IS: "Iceland",
  JM: "Jamaica",
  JO: "Jordan",
  KZ: "Kazakhstan",
  KI: "Kiribati",
  KW: "Kuwait",
  KG: "Kyrgyzstan",
  LA: "Laos",
  LV: "Latvia",
  LB: "Lebanon",
  LS: "Lesotho",
  LR: "Liberia",
  LY: "Libya",
  LT: "Lithuania",
  MG: "Madagascar",
  MW: "Malawi",
  MV: "Maldives",
  ML: "Mali",
  MH: "Marshall Islands",
  MR: "Mauritania",
  MU: "Mauritius",
  FM: "Micronesia",
  MD: "Moldova",
  MC: "Monaco",
  MN: "Mongolia",
  ME: "Montenegro",
  MA: "Morocco",
  MM: "Myanmar",
  NA: "Namibia",
  NR: "Nauru",
  NP: "Nepal",
  NI: "Nicaragua",
  NE: "Niger",
  NU: "Niue",
  KP: "North Korea",
  MK: "North Macedonia",
  OM: "Oman",
  PW: "Palau",
  PS: "Palestinian Territory",
  PA: "Panama",
  PG: "Papua New Guinea",
  PY: "Paraguay",
  PE: "Peru",
  QA: "Qatar",
  RW: "Rwanda",
  KN: "Saint Kitts and Nevis",
  LC: "Saint Lucia",
  VC: "Saint Vincent and the Grenadines",
  WS: "Samoa",
  ST: "Sao Tome and Principe",
  SC: "Seychelles",
  SL: "Sierra Leone",
  SB: "Solomon Islands",
  SO: "Somalia",
  SS: "South Sudan",
  LK: "Sri Lanka",
  SD: "Sudan",
  SR: "Suriname",
  SY: "Syria",
  TJ: "Tajikistan",
  TZ: "Tanzania",
  TL: "Timor-Leste",
  TG: "Togo",
  TO: "Tonga",
  TT: "Trinidad and Tobago",
  TN: "Tunisia",
  TM: "Turkmenistan",
  TV: "Tuvalu",
  UG: "Uganda",
  UA: "Ukraine",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VU: "Vanuatu",
  VE: "Venezuela",
  VN: "Vietnam",
  YE: "Yemen",
  ZM: "Zambia",
  ZW: "Zimbabwe",
};
